default: &default
  adapter: postgresql
  encoding: unicode
  database: casino_db
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  # <<: *default
  adapter: postgresql
  encoding: unicode
  database: casino_db
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  <<: *default
  database: casino_db_test

production:
  adapter: postgresql
  encoding: unicode
  database: casino_db_production
  host: localhost
  pool: 5
  username: root
  password: <%= ENV['CASINO_DB__DATABASE_PASSWORD'] %>
  role: myRole